version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: syfit
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: syed
      POSTGRES_DB: syfit_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
